// Widget listing page.
// Single data source: meta.json fetched from raw.githubusercontent.com (CDN, no rate limits).
// meta.json is auto-generated by GitHub Actions on every push to deploy.
//
// meta.json shape:
//   { folders: { "wgXX-name": { updatedAt, author }, ... },
//     commits:  [ { date, author, widgets: [71, 74, ...] }, ... ] }

const REPO = 'tce-ce6/widgets-ww';
const BRANCH = 'deploy';
const BASE_URL = 'https://tce-ce6.github.io/widgets-ww';
const META_URL = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/widget-listing-b3/data/meta.json`;

// ── User Aliases ───────────────────────────────────────────────────────────────
// Maps each raw GitHub username (case-sensitive) to a display alias.
// Multiple accounts belonging to the same person share one alias, so they are
// treated as a single user in filtering and history display.
const USER_ALIASES = {
  'sushantkanaujiya': 'sus',
  'sushantthe': 'sus',
  'PrasannaP': 'pkp',
  'Santosh': 'san',
  'Santosh Vishwakarma': 'san',
  'Shyam': 'shm',
  'aditya': 'adi',
  'tce-ashishg': 'ash',
  'tce-nitinc': 'nit',
};

/** Return the display alias for a raw author string, or the original if not mapped. */
function resolveAlias(author) {
  if (!author) return author;
  return USER_ALIASES[author] ?? author;
}

// ── Helpers ────────────────────────────────────────────────────────────────────
function titleCase(str) {
  return str.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function folderToWidget(name) {
  const num = (name.match(/^wg(\d+)/) || [])[1] || '';
  const raw = name.replace(/^wg\d+-?/, '');
  return {
    num,
    folder: name,
    title: raw ? titleCase(raw) : `Widget ${num}`,
    link: `${BASE_URL}/${name}/`,
    imagePath: `./widget-listing-b3/assets/wg-${num}.png`,
    updatedAt: null,
    author: null,
  };
}

function fmtDate(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  const p = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

async function loadMeta() {
  try {
    const res = await fetch(META_URL);
    if (!res.ok) return { folders: {}, commits: [] };
    const data = await res.json();
    // support both new { folders, commits } shape and legacy flat shape
    if (data.folders) return data;
    return { folders: data, commits: [] };
  } catch { return { folders: {}, commits: [] }; }
}

// ── Main ───────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', async () => {
  const listEl = document.getElementById('widget-listing');
  const totalEl = document.getElementById('total');
  const searchEl = document.getElementById('widget-search');
  const pageUpdEl = document.getElementById('page-updated');
  const recentActEl = document.getElementById('recent-activity');
  const sortChipsEl = document.getElementById('sort-chips');
  const userChipsEl = document.getElementById('user-chips');

  let widgets = [];
  let allCommits = [];       // full commits array from meta.json
  let activeSort = 'time';
  let activeUser = 'all';

  // ── Sorting ──────────────────────────────────────────────────────────────────
  function applySorted(arr) {
    const copy = [...arr];
    if (activeSort === 'time') {
      copy.sort((a, b) => {
        if (!a.updatedAt && !b.updatedAt) return parseInt(a.num) - parseInt(b.num);
        if (!a.updatedAt) return 1;
        if (!b.updatedAt) return -1;
        return new Date(b.updatedAt) - new Date(a.updatedAt);
      });
    } else if (activeSort === 'name') {
      copy.sort((a, b) => a.title.localeCompare(b.title));
    } else {
      copy.sort((a, b) => parseInt(a.num) - parseInt(b.num));
    }
    return copy;
  }

  // ── Card ─────────────────────────────────────────────────────────────────────
  function renderCard(w) {
    const li = document.createElement('li');
    li.dataset.folder = w.folder;
    li.innerHTML = `
      <a href="${w.link}">
        <img src="${w.imagePath}" alt="${w.title}">
        <span class="wg-num">wg${w.num}</span>
        <p class="widget-name">${w.title}</p>
        <span class="card-meta">
          ${w.updatedAt ? `<span class="card-ts">${fmtDate(w.updatedAt)}</span>` : ''}
          ${w.author ? `<span class="card-author">${w.author}</span>` : ''}
        </span>
      </a>`;
    return li;
  }

  // ── Render ───────────────────────────────────────────────────────────────────
  function render() {
    const q = searchEl.value.trim().toLowerCase();

    let filtered = applySorted(widgets);
    if (activeUser !== 'all') filtered = filtered.filter(w => w.author === activeUser);
    if (q) filtered = filtered.filter(w =>
      w.title.toLowerCase().includes(q) || w.num.includes(q)
    );

    totalEl.textContent = filtered.length;

    if (filtered.length === 0) {
      listEl.innerHTML = '<li class="loading-item"><span class="loading-text">No widgets match your search.</span></li>';
      return;
    }
    listEl.innerHTML = '';
    filtered.forEach(w => listEl.appendChild(renderCard(w)));
  }

  // ── Recent activity panel ─────────────────────────────────────────────────────
  // All-users mode: last 5 commits across everyone.
  // User selected: last 3 commits by that user.
  function buildActivityPanel(user) {
    if (!allCommits.length) { recentActEl.innerHTML = ''; return; }

    const rows = user === 'all'
      ? allCommits.slice(0, 5)
      : allCommits.filter(c => resolveAlias(c.author) === user).slice(0, 3);

    if (!rows.length) { recentActEl.innerHTML = ''; return; }

    const items = rows.map((c, i) => {
      const label = i === 0 ? 'Last&nbsp;Updated' : 'Updated';
      const nums = c.widgets.map(n => `<a class="act-wg" href="${BASE_URL}/wg${n}-*/" title="wg${n}">wg${n}</a>`).join(' ');
      // For user-filtered view, omit the author name (it's the selected chip)
      const who = user === 'all' ? `<span class="act-author">${resolveAlias(c.author)}</span>` : '';
      return `
        <div class="act-row${i === 0 ? ' act-row--first' : ''}">
          <span class="act-label">${label}</span>
          <span class="act-date">${fmtDate(c.date)}</span>
          ${who}
          <span class="act-widgets">(${c.widgets.join(', ')})</span>
        </div>`;
    });

    const heading = user === 'all'
      ? 'Recent Activity'
      : `${user} — Recent Activity`;

    recentActEl.innerHTML =
      `<h2 class="act-heading">${heading}</h2>` + items.join('');
  }

  // ── Page-level header subtitle (first commit) ─────────────────────────────────
  function setPageUpdated() {
    if (!allCommits.length) return;
    const c = allCommits[0];
    const nums = c.widgets.join(', ');
    pageUpdEl.textContent =
      `Updated ${fmtDate(c.date)}  ·  ${resolveAlias(c.author)}  (${nums})`;
  }

  // ── Sort chips ───────────────────────────────────────────────────────────────
  sortChipsEl.querySelectorAll('.chip').forEach(btn => {
    btn.addEventListener('click', () => {
      activeSort = btn.dataset.sort;
      sortChipsEl.querySelectorAll('.chip').forEach(c =>
        c.classList.toggle('active', c === btn)
      );
      render();
    });
  });

  // ── User chips ────────────────────────────────────────────────────────────────
  function buildUserChips(folders) {
    // Map raw authors → aliases, then de-duplicate so each person has one chip.
    const aliases = [...new Set(
      Object.values(folders)
        .map(m => resolveAlias(m.author))
        .filter(Boolean)
    )].sort();

    userChipsEl.innerHTML = '';
    if (!aliases.length) return;

    const label = document.createElement('span');
    label.className = 'chips-label';
    label.textContent = 'User';
    userChipsEl.appendChild(label);

    ['all', ...aliases].forEach(user => {
      const btn = document.createElement('button');
      btn.className = 'chip' + (user === activeUser ? ' active' : '');
      btn.dataset.user = user;
      btn.textContent = user === 'all' ? 'All Users' : user;
      btn.addEventListener('click', () => {
        activeUser = user;
        userChipsEl.querySelectorAll('.chip').forEach(c =>
          c.classList.toggle('active', c.dataset.user === user)
        );
        buildActivityPanel(activeUser);
        render();
      });
      userChipsEl.appendChild(btn);
    });
  }

  // ── Single fetch: meta.json from raw.githubusercontent.com (no API, no rate limits) ──
  listEl.innerHTML =
    '<li class="loading-item"><span class="loading-text">Loading widgets…</span></li>';

  const meta = await loadMeta();
  allCommits = meta.commits || [];
  const folders = meta.folders || {};

  if (!Object.keys(folders).length) {
    listEl.innerHTML =
      '<li class="loading-item"><span class="loading-text">No widget data yet — meta.json will be populated after the next push to deploy.</span></li>';
    totalEl.textContent = '0';
    return;
  }

  widgets = Object.keys(folders)
    .filter(name => /^wg\d+/.test(name))
    .map(name => {
      const w = folderToWidget(name);
      const info = folders[name];
      w.updatedAt = info.updatedAt;
      w.author = resolveAlias(info.author);  // normalise to alias
      return w;
    })
    .sort((a, b) => parseInt(a.num) - parseInt(b.num));

  setPageUpdated();
  buildActivityPanel('all');
  buildUserChips(folders);
  render();
  searchEl.addEventListener('input', render);
});
