// Auto-discovers wg* folders via GitHub API (1 call).
// Timestamps and authors come from a pre-built meta.json generated by a
// GitHub Actions workflow on every push — no per-widget API calls, no rate limits.

const REPO     = 'tce-ce6/widgets-ww';
const BRANCH   = 'deploy';
const BASE_URL = 'https://tce-ce6.github.io/widgets-ww';
const API_BASE = `https://api.github.com/repos/${REPO}`;
const META_URL = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/widget-listing-b3/data/meta.json`;

// ── Helpers ────────────────────────────────────────────────────────────────────
function titleCase(str) {
  return str.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function folderToWidget(name) {
  const num   = (name.match(/^wg(\d+)/) || [])[1] || '';
  const raw   = name.replace(/^wg\d+-?/, '');
  return {
    num,
    folder:    name,
    title:     raw ? titleCase(raw) : `Widget ${num}`,
    link:      `${BASE_URL}/${name}/`,
    imagePath: `./widget-listing-b3/assets/wg-${num}.png`,
    updatedAt: null,
    author:    null,
  };
}

function fmtDate(iso) {
  if (!iso) return '';
  const d   = new Date(iso);
  const p   = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

// ── Meta loading (single fetch from raw.githubusercontent.com) ─────────────────
async function loadFolderMeta() {
  try {
    const res = await fetch(META_URL);
    if (!res.ok) return {};
    return await res.json();
  } catch {
    return {};
  }
}

// ── Main ───────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', async () => {
  const listEl   = document.getElementById('widget-listing');
  const totalEl  = document.getElementById('total');
  const searchEl = document.getElementById('widget-search');

  listEl.innerHTML =
    '<li class="loading-item"><span class="loading-text">Loading widgets…</span></li>';

  // 1. Discover all wg* folders (1 API call)
  let widgets = [];
  try {
    const res = await fetch(`${API_BASE}/contents/?ref=${BRANCH}`);
    if (!res.ok) throw new Error(`GitHub API ${res.status}`);
    const items = await res.json();
    if (!Array.isArray(items)) throw new Error(items.message || 'Unexpected API response');

    widgets = items
      .filter(i => i.type === 'dir' && /^wg\d+/.test(i.name))
      .map(i => folderToWidget(i.name))
      .sort((a, b) => parseInt(a.num) - parseInt(b.num));
  } catch (err) {
    listEl.innerHTML = `<li class="loading-item">
      <span class="loading-text">Could not load widgets — ${err.message}</span></li>`;
    totalEl.textContent = '0';
    console.error(err);
    return;
  }

  // 2. Render immediately (no timestamps yet)
  function renderCard(w) {
    const li = document.createElement('li');
    li.dataset.folder = w.folder;
    li.innerHTML = `
      <a href="${w.link}">
        <img src="${w.imagePath}" alt="${w.title}">
        <span class="wg-num">wg${w.num}</span>
        <p class="widget-name">${w.title}</p>
        <span class="updated-date">
          ${w.updatedAt ? `<span class="upd-ts">${fmtDate(w.updatedAt)}</span>` : ''}
          ${w.author    ? `<span class="upd-author">${w.author}</span>`          : ''}
        </span>
      </a>`;
    return li;
  }

  function render() {
    const q        = searchEl.value.trim().toLowerCase();
    const filtered = q
      ? widgets.filter(w => w.title.toLowerCase().includes(q) || w.num.includes(q))
      : widgets;

    totalEl.textContent = filtered.length;

    if (filtered.length === 0) {
      listEl.innerHTML = '<li class="loading-item"><span class="loading-text">No widgets match your search.</span></li>';
      return;
    }

    listEl.innerHTML = '';
    filtered.forEach(w => listEl.appendChild(renderCard(w)));
  }

  render();
  searchEl.addEventListener('input', render);

  // 3. Load timestamps + author from pre-built meta.json (single request, no rate limits)
  const meta = await loadFolderMeta();

  widgets.forEach(w => {
    const info = meta[w.folder];
    if (!info) return;
    w.updatedAt = info.date;
    w.author    = info.author;

    const li = listEl.querySelector(`[data-folder="${w.folder}"]`);
    if (!li) return;
    const badge = li.querySelector('.updated-date');
    if (!badge) return;
    badge.innerHTML =
      (info.date   ? `<span class="upd-ts">${fmtDate(info.date)}</span>` : '') +
      (info.author ? `<span class="upd-author">${info.author}</span>`     : '');
  });
});
