const DATA = [
  {phrase:"जिसके समान कोई दूसरा न हो", answer:"अद्वितीय", phraseAudio:"audio/phrase_01.mp3", wordAudio:"audio/word_01.mp3"},
  {phrase:"जिसकी आशा न की गई हो", answer:"अप्रत्याशित", phraseAudio:"audio/phrase_02.mp3", wordAudio:"audio/word_02.mp3"},
  {phrase:"जो इन्द्रियों से परे हो", answer:"अगोचर", phraseAudio:"audio/phrase_03.mp3", wordAudio:"audio/word_03.mp3"},
  {phrase:"जो विधान के विपरीत हो", answer:"अवैधानिक", phraseAudio:"audio/phrase_04.mp3", wordAudio:"audio/word_04.mp3"},
  {phrase:"जो संविधान के प्रतिकूल हो", answer:"असंवैधानिक", phraseAudio:"audio/phrase_05.mp3", wordAudio:"audio/word_05.mp3"},
  {phrase:"जिसे भले-बुरे का ज्ञान न हो", answer:"अविवेकी", phraseAudio:"audio/phrase_06.mp3", wordAudio:"audio/word_06.mp3"},
  {phrase:"जिसे वाणी व्यक्त न कर सके", answer:"अनिर्वचनीय", phraseAudio:"audio/phrase_07.mp3", wordAudio:"audio/word_07.mp3"},
  {phrase:"जैसा पहले कभी न हुआ हो", answer:"अभूतपूर्व", phraseAudio:"audio/phrase_08.mp3", wordAudio:"audio/word_08.mp3"},
  {phrase:"जो व्यर्थ का व्यय करता हो", answer:"अपव्ययी", phraseAudio:"audio/phrase_09.mp3", wordAudio:"audio/word_09.mp3"},
  {phrase:"बहुत कम खर्च करने वाला", answer:"मितव्ययी", phraseAudio:"audio/phrase_10.mp3", wordAudio:"audio/word_10.mp3"},
  {phrase:"जिसके पास कुछ भी न हो", answer:"अकिंचन", phraseAudio:"audio/phrase_11.mp3", wordAudio:"audio/word_11.mp3"},
  {phrase:"जिसका निवारण न हो सके", answer:"अनिवार्य", phraseAudio:"audio/phrase_12.mp3", wordAudio:"audio/word_12.mp3"},
  {phrase:"जिसका परिहार करना सम्भव न हो", answer:"अपरिहार्य", phraseAudio:"audio/phrase_13.mp3", wordAudio:"audio/word_13.mp3"},
  {phrase:"जिसे प्राप्त न किया जा सके", answer:"अप्राप्य", phraseAudio:"audio/phrase_14.mp3", wordAudio:"audio/word_14.mp3"},
  {phrase:"जिसका उपचार सम्भव न हो", answer:"असाध्य", phraseAudio:"audio/phrase_15.mp3", wordAudio:"audio/word_15.mp3"},
  {phrase:"जो तुरंत कविता बना सके", answer:"आशुकवि", phraseAudio:"audio/phrase_16.mp3", wordAudio:"audio/word_16.mp3"},
  {phrase:"जो दूसरों के दोष खोजे", answer:"छिद्रान्वेषी", phraseAudio:"audio/phrase_17.mp3", wordAudio:"audio/word_17.mp3"},
  {phrase:"इन्द्रियों को जीतने वाला", answer:"जितेन्द्रिय", phraseAudio:"audio/phrase_18.mp3", wordAudio:"audio/word_18.mp3"},
  {phrase:"जो त्यागने योग्य हो", answer:"त्याज्य", phraseAudio:"audio/phrase_19.mp3", wordAudio:"audio/word_19.mp3"},
  {phrase:"जिसे पार करना कठिन हो", answer:"दुस्तर", phraseAudio:"audio/phrase_20.mp3", wordAudio:"audio/word_20.mp3"},
  {phrase:"जिसमें कोई विवाद ही न हो", answer:"निर्विवाद", phraseAudio:"audio/phrase_21.mp3", wordAudio:"audio/word_21.mp3"},
  {phrase:"रात्रि में विचरण करने वाला", answer:"निशाचर", phraseAudio:"audio/phrase_22.mp3", wordAudio:"audio/word_22.mp3"},
  {phrase:"किसी विषय का पूर्ण ज्ञाता", answer:"पारंगत", phraseAudio:"audio/phrase_23.mp3", wordAudio:"audio/word_23.mp3"},
  {phrase:"जिसे तुरंत उचित उत्तर सूझ जाए", answer:"प्रत्युत्पन्नमति", phraseAudio:"audio/phrase_24.mp3", wordAudio:"audio/word_24.mp3"},
  {phrase:"मोक्ष का इच्छुक", answer:"मुमुक्षु", phraseAudio:"audio/phrase_25.mp3", wordAudio:"audio/word_25.mp3"},
  {phrase:"युद्ध की इच्छा रखने वाला", answer:"युयुत्सु", phraseAudio:"audio/phrase_26.mp3", wordAudio:"audio/word_26.mp3"},
  {phrase:"जो क्षण भर में नष्ट हो जाए", answer:"क्षणभंगुर", phraseAudio:"audio/phrase_27.mp3", wordAudio:"audio/word_27.mp3"},
  {phrase:"जिसका मन दूसरी ओर हो", answer:"अन्यमनस्क", phraseAudio:"audio/phrase_28.mp3", wordAudio:"audio/word_28.mp3"},
  {phrase:"जो कार्य कठिनता से हो सके", answer:"दुष्कर", phraseAudio:"audio/phrase_29.mp3", wordAudio:"audio/word_29.mp3"},
  {phrase:"जिसने किसी दूसरे का स्थान अस्थाई रूप से ग्रहण किया हो", answer:"स्थानापन्न", phraseAudio:"audio/phrase_30.mp3", wordAudio:"audio/word_30.mp3"}
];


